{
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\PC\\AppData\\Roaming',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: '133956161257631604',
  CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_6672_EMLKFIESFVJVFVFC',
  COLOR: '1',
  COLORTERM: 'truecolor',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'RAVI-PC',
  ComSpec: 'C:\\Windows\\system32\\cmd.exe',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  EDITOR: 'C:\\Windows\\notepad.exe',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  GIT_ASKPASS: 'c:\\Users\\PC\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
  HOME: 'C:\\Users\\PC',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\PC',
  INIT_CWD: 'E:\\backend\\backend-hitesh\\finalProject',
  LANG: 'en_US.UTF-8',
  LOCALAPPDATA: 'C:\\Users\\PC\\AppData\\Local',
  LOGONSERVER: '\\\\RAVI-PC',
  NODE: 'C:\\Program Files\\nodejs\\node.exe',
  npm_command: 'run-script',
  npm_config_cache: 'C:\\Users\\PC\\AppData\\Local\\npm-cache',
  npm_config_globalconfig: 'C:\\Users\\PC\\AppData\\Roaming\\npm\\etc\\npmrc',
  npm_config_global_prefix: 'C:\\Users\\PC\\AppData\\Roaming\\npm',
  npm_config_init_module: 'C:\\Users\\PC\\.npm-init.js',
  npm_config_local_prefix: 'E:\\backend\\backend-hitesh\\finalProject',
  npm_config_node_gyp: 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
  npm_config_noproxy: '',
  npm_config_npm_version: '10.9.2',
  npm_config_prefix: 'C:\\Users\\PC\\AppData\\Roaming\\npm',
  npm_config_userconfig: 'C:\\Users\\PC\\.npmrc',
  npm_config_user_agent: 'npm/10.9.2 node/v22.17.0 win32 x64 workspaces/false',
  npm_execpath: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
  npm_lifecycle_event: 'dev',
  npm_lifecycle_script: 'nodemon src/index.js',
  npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
  npm_package_json: 'E:\\backend\\backend-hitesh\\finalProject\\package.json',
  npm_package_name: 'chai-backend',
  npm_package_version: '1.0.0',
  NUMBER_OF_PROCESSORS: '4',
  OneDrive: 'C:\\Users\\PC\\OneDrive',
  ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
  OS: 'Windows_NT',
  Path: 'E:\\backend\\backend-hitesh\\finalProject\\node_modules\\.bin;E:\\backend\\backend-hitesh\\node_modules\\.bin;E:\\backend\\node_modules\\.bin;E:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Users\\PC\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\PC\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\PC\\AppData\\Roaming\\npm;C:\\Users\\PC\\AppData\\Local\\GitHubDesktop\\bin',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '3a09',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSModulePath: 'C:\\Users\\PC\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'C:\\Users\\Public',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\Windows',
  TEMP: 'C:\\Users\\PC\\AppData\\Local\\Temp',
  TERM_PROGRAM: 'vscode',
  TERM_PROGRAM_VERSION: '1.103.2',
  TMP: 'C:\\Users\\PC\\AppData\\Local\\Temp',
  USERDOMAIN: 'RAVI-PC',
  USERDOMAIN_ROAMINGPROFILE: 'RAVI-PC',
  USERNAME: 'PC',
  USERPROFILE: 'C:\\Users\\PC',
  VSCODE_GIT_ASKPASS_EXTRA_ARGS: '',
  VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\PC\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
  VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\PC\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
  VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-3906920cce-sock',
  VSCODE_INJECTION: '1',
  windir: 'C:\\Windows'
}